source/longtermschedule.rst

various improvements to long-term schedule

---

source/currentschedule.rst
source/fallmobile.rst
source/schedules/fall2015mobile.inc

This is only the mobile version, since it was easier to create a Scala script for. I wanted to upload this quickly!

Added Fall 2015 schedule

---

source/schedules/fall2015mobile.inc
source/schedules/fall2015widescreen.inc

Made changes recommended by Dr. Harrington.

Minor changes to Fall 2015 schedule.

---

source/longtermschedule.rst

Signed-off-by: Konstantin Läufer <laufer@cs.luc.edu>

updated for fall 2015

---

source/comp122.rst
source/comp384.rst
source/comp386.rst
source/comp397.rst
source/index.rst
source/longtermschedule.rst

added pages for 122, 384, 386, 397 and added to index and LTS

---

source/schedules/fall2015mobile.inc
source/schedules/fall2015widescreen.inc

Changed Fall 2015 schedule to reflect Trello card #260

---

source/index.rst
source/minorit.rst

Added IT Minor to index, as per Trello card #264

---

source/comp388.rst
source/schedules/fall2015mobile.inc
source/schedules/fall2015widescreen.inc

Added courses notes as per Trello card #258

---

source/schedules/fall2015mobile.inc
source/schedules/fall2015widescreen.inc

minor instructor changes

---

source/longtermschedule.rst

moved 363 to fall + spring

---

source/longtermschedule.rst

Signed-off-by: Konstantin Läufer <laufer@cs.luc.edu>

updated plans for 324/424

---

source/comp288.rst
source/comp322.rst
source/comp379.rst
source/comp388.rst
source/comp488.rst
source/index.rst
source/longtermschedule.rst

added several missing permanent courses, updated 388/488

---

source/comp451.rst
source/index.rst

merged Dennis's changes

---

csv2sched.py
fall2016.csv
source/fall.rst

Added fall2016 schedule and changed fall schedule link to new format. Now Fall2016 schedule page is a web page instead of PDF file.
Removed textbook link from fall schedule page .

Added fall2016 schedule and changed fall schedule link to new format.

---

source/index.rst

Signed-off-by: Konstantin Läufer <klaeufer@gmail.com>

added COMP 180 to index

---

source/index.rst
source/msit.rst
source/oldtracks.rst

Signed-off-by: Konstantin Läufer <klaeufer@gmail.com>

fixed refs to old MSIT tracks

---

csv2sched.py
fall2017(deprecated).csv
source/cuneoFall.rst
source/fall.rst
source/lakeShorefall.rst
source/onlineFall.rst
source/waterTowerFall.rst

Updated fall 2017 schedule and modified csv2sched.py to take file name as input

update fall 2017 schedule

---

source/bsse.rst

Update Software Engineering Suggested Ordering of Courses

Update Software Engineering Suggested Ordering of Courses

---

fall_2018_updated.csv
source/cuneoFall.rst
source/lakeShoreFall.rst
source/onlineFall.rst
source/waterTowerFall.rst

update fall 2018 schedule

---

source/bsse.rst
source/comp381.rst

Changes to BSSE page and comp381.

Undergrad update

---

source/fall.rst
source/lakeShorefall.rst
source/onlineFall.rst
source/waterTowerFall.rst

most recent csv generation

---

Spring2019(Old).csv
source/lakeshorespring.rst
source/onlinespring.rst
source/spring.rst
source/watertowerspring.rst

newest rsts refer to the most recent spring csv.

newest spring scheduele

---

.idea/workspace.xml
source/Summer2019.csv

Summer2019.csv file added and ran the script.

Summer2019.csv file added

---

source/schedules/fall2019/fall.rst
source/schedules/fall2019/lakeshorefall.rst
source/schedules/fall2019/onlinefall.rst
source/schedules/fall2019/watertowerfall.rst
source/schedules/schedules.rst
source/schedules/summer2019/watertowersummer.rst

Added more to the schedule page so the users can get to the term schedules. I also fixed the links to courses in the schedules that were broken due to the new server structure.

Fixed and added several things

---

source/schedules/schedules.rst

Fixed a error I made by accident

fixed small error

---

source/graduate/common_program_features.inc
source/graduate/masters_overview.rst

Fixed grad handbook links within sphinx pages

changed grad handbook links

---

source/graduate/masters_overview.rst

Fix for issue #3

---

.github/workflows/main.yml

Update branch for the workflow to be executed on from `main` to `master`

Update branch for the workflow to be executed on

---

source/courses/comp429.rst
source/courses/comp450.rst
source/courses/comp458.rst
source/graduate/graduate-degree-programs.rst
source/undergraduate/bsit.rst
source/undergraduate/bsse.rst

Resolved issues:
* #180 
* #181  
* #183 
* #184 
* #185

Resolve issues
